### ISSUE TITLE
Skip 7.3 CRAN release and go straight to 7.4(?)

### ISSUE THREAD

**Issue by lianos** [igordot/msigdbr#16]
It looks like the MSigDB [v7.4 signature collection](https://software.broadinstitute.org/cancer/software/gsea/wiki/index.php?title=MSigDB_v7.4_Release_Notes) have been released before an msigdbr version for the v7.3 signatures has been pushed to CRAN. Maybe skip a v7.3 msigdbr release and go straight to the v7.4 signatures for the next CRAN release?

Thanks!

**Comment by igordot** [comment]
I ran into some CRAN submission issues, which explains why 7.3 is not on CRAN. 7.4 will be next and hopefully soon.
