### ISSUE TITLE
MSigDB 7.4

### ISSUE THREAD

**Issue by kvittingseerup** [igordot/msigdbr#17]
It seems MSigDB 7.4 [has been released](https://software.broadinstitute.org/cancer/software/gsea/wiki/index.php/MSigDB_Latest_Release_Notes). Are there plans to soon update msigdbr?

**Comment by lianos** [comment]
[This is on the author's radar](https://github.com/igordot/msigdbr/issues/16), but I suspect he's a bit swamped at the moment.

**Comment by igordot** [comment]
Yes, an update is coming.

**Comment by igordot** [comment]
The version based on 7.4 is now available.

**Comment by kvittingseerup** [comment]
Nice! Thanks :-)
