### ISSUE TITLE
msigdbr package, category C2, subcategory CP

### ISSUE THREAD

**Issue by acaulier** [igordot/msigdbr#20]
Hello,
I'm currently running a gsea using msigdbr package. 
I've noticed that subcategory CP of category C2 only contains 29 gene sets as displayed by msigdbr(collections), whereas this subcategory should include all of the depending gene sets (KEGG, reactome, wikipthways,...) and originally contains 2982 gene sets, as detailed on the original website : http://www.gsea-msigdb.org/gsea/msigdb/genesets.jsp?collection=CP

Any recommendations to run all of these gene sets depending on CP subcategory?

Thank you!

**Comment by igordot** [comment]
You are correct. CP is one of the non-standard categories. Although on the MSigDB website you can see 3 levels, the data is provided as 2 levels (likely for historical reasons). CP is broken up into multiple subsets such as "CP:BIOCARTA".

If you are ever not sure about the categories, there is a `msigdbr_collections()` function to help with troubleshooting.

```
> msigdbr::msigdbr_collections()
# A tibble: 23 × 3
   gs_cat gs_subcat         num_genesets
   <chr>  <chr>                    <int>
 1 C1     ""                         299
 2 C2     "CGP"                     3384
 3 C2     "CP"                        29
 4 C2     "CP:BIOCARTA"              292
 5 C2     "CP:KEGG"                  186
 6 C2     "CP:PID"                   196
 7 C2     "CP:REACTOME"             1615
 8 C2     "CP:WIKIPATHWAYS"          664
 9 C3     "MIR:MIR_Legacy"           221
10 C3     "MIR:MIRDB"               2377
```

**Comment by acaulier** [comment]
Thank you Igor,

So, my aim would be to run GSEA on all of the "CP:xxx” subcategories at once; is there any way to combine these gene sets in one? So I can test my gene list on all the CP-depending pathways at once.

Thank you,

Alexis 

Alexis Caulier MD, PhD
Research Fellow - Vijay Sankaran Lab
Boston Children’s Hospital, Harvard Medical School
KARP Building, 1 Blackfan Street MA 02115 BOSTON
Email : ***@***.***
            ***@***.***

**Comment by igordot** [comment]
The output is a standard data frame so you can filter it with any tools that work with data frames.

You can retrieve each one and combine with `dplyr::bind_rows()`.

You can also retrieve all and subset:

```
> m_all = msigdbr::msigdbr()
> m_cp = dplyr::filter(m_all, stringr::str_detect(gs_subcat, "^CP"))
> dplyr::count(dplyr::distinct(m_cp, gs_subcat, gs_name), gs_subcat)
# A tibble: 6 × 2
  gs_subcat           n
  <chr>           <int>
1 CP                 29
2 CP:BIOCARTA       292
3 CP:KEGG           186
4 CP:PID            196
5 CP:REACTOME      1615
6 CP:WIKIPATHWAYS   664
```

**Comment by acaulier** [comment]
Incredibly helpful, I used the filter function of dplyr as suggested and was able to test all CP sub at once.

Thanks a lot Igor!



Alexis Caulier MD, PhD
Research Fellow - Vijay Sankaran Lab
Boston Children’s Hospital, Harvard Medical School
KARP Building, 1 Blackfan Street MA 02115 BOSTON
Email : ***@***.***
            ***@***.***
