### ISSUE TITLE
Some orthologs are missing

### ISSUE THREAD

**Issue by ashuchawla** [igordot/msigdbr#3]
Hi, 

I am trying to use msigdbr for a GSEA analysis for the GENESET - **HSF1_01** in MSigDB.

Now this geneset contains a gene **SHFM3** in MSigDB but it is missing in your list of orthologs for the same geneset. 

I did a search for this gene - https://uswest.ensembl.org/Multi/Search/Results?q=SHFM3;site=ensembl

And found out that this gene has an alias/synonym - **FBXW4** (as shown here - > https://uswest.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000107829;r=10:101610664-101695295 )

This particular alias (FBXW4) does have ORTHOLOG information for mus musculus (**Fbxw4**) as shown at - https://uswest.ensembl.org/Homo_sapiens/Gene/Compara_Ortholog?db=core;g=ENSG00000107829;r=10:101610664-101695295

There are many such cases and I was wondering if that is intentional or could be fixed in the future releases?

Much appreciate!

Ashu

**Comment by igordot** [comment]
This is an interesting example. Gene set [HSF1_01](http://software.broadinstitute.org/gsea/msigdb/geneset_page.jsp?geneSetName=HSF1_01) has SHFM3 listed with [Entrez Gene ID 100049542](https://www.ncbi.nlm.nih.gov/gene/100049542) where FBXW4 is not given as its synonym. The SHFM3 entry on [GeneCards](https://www.genecards.org/cgi-bin/carddisp.pl?gene=SHFM3) also does not mention FBXW4. 

For `msigdbr`, the gene information is retrieved from [HCOP](https://www.genenames.org/tools/hcop/) where SHFM3 is not listed. I am assuming that all MSigDB genes have valid gene symbols and Entrez Gene IDs.

Hope this clarifies the situation.

**Comment by ashuchawla** [comment]
Thank you so much for your prompt reply and the clarification. After checking the links provided by you I understand that **SHFM3** is actually an old/previous symbol used for the gene **FBXW4**.

If you search for **SHFM3** at https://www.genenames.org/tools/multi-symbol-checker/ , following pops up - 


Input | Match type | Approved symbol | Approved name | HGNC ID | Location
-- | -- | -- | -- | -- | --
SHFM3 | Previous symbol | FBXW4 | F-box and WD repeat domain containing 4 | HGNC:10847 | 10q24.32


I am unsure if it is OK to ignore this particular gene just because MSigDB has an old name for it. I guess the number of such genes are very low in a geneset and the GSEA results should not change much if we miss these genes.

Thanks again!

Ashu

**Comment by igordot** [comment]
MSigDB has it listed as [Entrez Gene ID 100049542](https://www.ncbi.nlm.nih.gov/gene/100049542). This is a different gene than FBXW4, which is listed as [Entrez Gene ID 6468](https://www.ncbi.nlm.nih.gov/gene/6468). While it's true that SHFM3 is a synonym for both of those, I am assuming that MSigDB has the correct ID listed.

I agree that the number of such genes is probably relatively low. It's also possible that there are unambiguous genes in any gene set that really do not belong there. One of the benefits of pathway analysis is aggregating data across many genes and minimizing the effects of individual genes.

**Comment by rauldiul** [comment]
Hi, 

sorry to expand on this question, but could you provide further clarification as to how genes with **1:many orthologs** in human:mouse (or other species) have been cleaned up?

For example, in a particular geneset, if a gene showed in HCOP a unique human EntrezID but >1 mouse EntrezIDs, did you:

- include all of the different mouse EntrezIDs in the gene set 
- only included 1 of the mouse EntrezIDs, (if so, which one)
- etc.

thanks for your help
