### ISSUE TITLE
Run KEGG in Seurat object

### ISSUE THREAD

**Issue by krigia** [igordot/msigdbr#31]
@igordot @smped @vreuter @actions-user 

Hello msigdbr team,

I am running GSEA analysis in 10X spatial and scRNA-seq data and I would like to use KEGG dataset.
Which function/category should I run?
For Hallmark, I run m_df<- msigdbr(species = "Homo sapiens", category = "H")

but category = "KEGG" does not work. I would greatly appreciate your advice. 

Thank you.

**Comment by igordot** [comment]
You can check the available collections with `msigdbr_collections()`.

You will see that for KEGG, you want to use `msigdbr(species = "Homo sapiens", category = "C2", subcategory = "CP:KEGG")`.
