### ISSUE TITLE
C2:CGP pathways being labelled as C2:CP pathways

### ISSUE THREAD

**Issue by rauldiul** [igordot/msigdbr#35]
Hi!

thanks for the great software.

I'm using the latest version (`v7.5.1`), and when I load the gene sets as such: `sets <- as.data.frame(msigdbr(species = "Homo sapiens"))`, I have seen that there are some pathways labelled with `gs_subcat == CP` but which are actually from `gs_subcat == CGP`. One example are pathways from the NABA study: `NABA_BASEMENT_MEMBRANES`, `NABA_MATRISOME`, etc. These are listed as CGP pathways in the MSigDB website (e.g.: https://www.gsea-msigdb.org/gsea/msigdb/cards/NABA_MATRISOME).

What do you think could have happened for these CGP pathways to end up labelled as CP within `msigdbr` and do you think you can provide a solution for this?

thanks a lot!

**Comment by igordot** [comment]
The gene sets can change categories between different versions of MSigDB. Although NABA_MATRISOME is in CGP now, it used to be in CP (see [archived gene set page](https://web.archive.org/web/20210804081359/https://www.gsea-msigdb.org/gsea/msigdb/cards/NABA_MATRISOME)).
