### ISSUE TITLE
Missing pathways in results

### ISSUE THREAD

**Issue by emmanuel-contreras** [igordot/msigdbr#37]
Hello,
I'm not sure if this is a bug or outdated database but the list of pathways coming from msigdbr seem to be incomplete.

The pathways I was look at were go:bp and I cannot find _GOBP_CELLULAR_CATABOLIC_PROCESS_ within the results
https://www.gsea-msigdb.org/gsea/msigdb/human/genesets.jsp?collection=GO:BP

``` R
library(msigdbr)
msigdbr_df_gobp=msigdbr(species = "Homo sapiens",category = "C5", subcategory = "GO:BP")
msigdbr_df_gobp[msigdbr_df_gobp$gs_name == 'GOBP_CELLULAR_CATABOLIC_PROCESS',]
```

**Comment by igordot** [comment]
Looks like this is due to version differences. GOBP_CELLULAR_CATABOLIC_PROCESS is a recent addition.
