### ISSUE TITLE
Problem with loading several categories

### ISSUE THREAD

**Issue by laurie-tonon** [igordot/msigdbr#5]
In our work we often want to test our gene lists against several categories of gene sets at once.
Until now we would load the gene sets like this:
```
msigdb.genes.sets <-msigdbr(species="Homo sapiens", category=c("H","C2"))
```
We noticed that in doing so, the gene sets are truncated, with a remaining number of genes in a gene set varying with the number of categories or their order.
After looking at the R code it seems the problem is that the categories are filtered with an "==" and not a "%in%, which means we cannot use an array in our command. But no warning or error is thrown and everything downstream works, with background ratio values wrong obviously.

Would it be possible to correct this or to forbid requesting more than one category in the command?

**Comment by igordot** [comment]
Thank you for pointing this out. I did not expect multiple categories to be requested, but that scenario should definitely be handled better.

**Comment by igordot** [comment]
I disabled the ability to request more than one category/subcategory in the latest release, which is now on CRAN.

You can still use `dplyr::filter()` or `dplyr::bind_rows()` to combine any subsets.
