### ISSUE TITLE
Update to MSIGDB

### ISSUE THREAD

**Issue by millerh1** [igordot/msigdbr#6]
Hello! 

I was wondering if there were plans to synchronize msigdbr with the latest release of MSIGDB (aug 2019)? The new MSIGDB has added and removed hundreds of gene sets so I've been finding that the information pages for most of my top GSEA hits using msgidbr annotations no longer exist. 

Thank you for your time!
Best,
Henry

**Comment by igordot** [comment]
The latest release has been updated to MSigDB 7.0 and is now available on CRAN and GitHub.
