### ISSUE TITLE
Archived genesets

### ISSUE THREAD

**Issue by millerh1** [igordot/msigdbr#7]
Hello!

Is there any way msigdbr could be used to access archived genesets? i.e. those belonging to the "ARCHIVED" collection such as [PENG_GLUTAMINE_DEPRIVATION_DN](http://software.broadinstitute.org/gsea/msigdb/cards/PENG_GLUTAMINE_DEPRIVATION_DN.html)

Best,
Henry

**Comment by igordot** [comment]
That is not currently possible (as you probably already discovered).

I am not sure how hard it would be to add. I don't think the archived gene sets are easily accessible. For example, it's possible to [download older releases of MSigDB](http://software.broadinstitute.org/gsea/downloads_archive.jsp), but the archived ones are not explicitly labeled there. You could check which gene sets disappear, but that would not account for gene sets that were modified.

**Comment by millerh1** [comment]
Understood! Thanks!

Best,
Henry
