### ISSUE TITLE
Retrieve all C2 canonical pathways using option subcategory = "CP"?

### ISSUE THREAD

**Issue by lxhuang7** [igordot/msigdbr#9]
Dear Igordot,

Thanks for this wonderful tool! I understand it can be used to retrieve subcategory pathways by setting subcategory = "CP:KEGG". But I was wondering if I can extract all canonical pathways as follows:

> library(msigdbr)
> m_df = msigdbr(species = "Homo sapiens", category = 'C2', subcategory = 'CP')
> length(unique(m_df$gs_name))
[1] 29

Looking forward to your comments!

Best,
Lei

**Comment by lxhuang7** [comment]
Oh I found out from the closed issues that the software doesn't support this, but we can add a filter to do so. Thanks again for this package.

**Comment by igordot** [comment]
Glad to hear you were able to resolve this yourself.

If anyone ends up on this page later, the original issue with the solution is here: https://github.com/igordot/msigdbr/issues/4
